#!/usr/bin/python2

# program that makes entry of ip and hostname of vms in /etc/hosts so that pinging by hostname is possible

import commands,libvirt,json

conn=libvirt.open("qemu:///system")

ids = conn.listDomainsID()
l = len(ids)

# get domain name of vms
names = []
for i in ids:
        lookup=conn.lookupByID(i)
        info=lookup.info()
        nm=lookup.name()
        names.append(nm)

names.sort()

def get_ip(vm_name):
        ip = commands.getstatusoutput('virsh domifaddr '+vm_name)
        ip = ip[1].split('\n')[2].split(' ')[-1].split('/')[0]
	return ip
	
remove = commands.getstatusoutput('rm -f /etc/hosts ')
copy = commands.getstatusoutput('cp /etc/hosts.backup /etc/hosts')

if copy[0]==0:
	print "Successfully created /etc/hosts"

for i in range(0,l):
	ip = get_ip(names[i])
	command = 'echo '+ip+' node'+str(i+1)+' >> /etc/hosts'
        entry = commands.getstatusoutput(command)
	if entry[0]==0:
		print 'done entry of node'+str(i+1)










	 
	
               





